name: Relase Binaries

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  windows:
    runs-on: windows-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create binaries
      run: |
        pip3 install pyinstaller
        pip3 install -r requirements.txt
        cd nordicsemi
        pyinstaller __main__.py --onefile --clean --name adafruit-nrfutil
        cd dist
        7z a -tzip ../../adafruit-nrfutil--${{ github.event.release.tag_name }}-win.zip adafruit-nrfutil.exe

    - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-tool.zip
          path: ../../adafruit-nrfutil--${{ github.event.release.tag_name }}-win.zip 
